In [1]:
import numpy as np

# Creación de arrays NumPy
A partir de secuencias de Python

In [2]:
a = np.array([1, 2.5, 3])
a

array([1. , 2.5, 3. ])

In [3]:
b = np.array([[1, 2, 3],
             [4, 5, 6 ]])
b

array([[1, 2, 3],
       [4, 5, 6]])

Atributos de **ndarray**

In [4]:
# dimensiones
print(a.ndim)
print(b.ndim)
# forma
print(a.shape)
print(b.shape)
# número de elementos
print(a.size)
print(b.size)
# tipo de dato
print(a.dtype)
print(b.dtype)
# tamaño de cada elemento
print(a.itemsize)
print(b.itemsize)

1
2
(3,)
(2, 3)
3
6
float64
int64
8
8


Se puede especificar el tipo de dato

In [5]:
c = np.array([1, 2, 3], dtype= np.float64)
print(c)
print(c.dtype)


[1. 2. 3.]
float64


NumPy tiene varias funciones para crear arrays:


1.   ones(shape, dtype=None, order='C', *, like=None) crea un array lleno de unos.
2.   zeros(shape, dtype=None, order='C', *, like=None) crea un array lleno de zeros.
3.   empty(shape, dtype=None, order='C', *, like=None) crear un array sin inicializar.
4.   arange([start, ]stop, [step, ]dtype=None, *, like=None) crea un array con valores espaciados dentro de un intervalo.
5.   linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0), similar a la anterior.

Las tres primeras tienen los mismos argumentos:

numpy.ones(shape, dtype=None, order='C', *, like=None)


El más importante es shape, un entero o tupla de enteros con la forma (shape) del array.



In [6]:
unos1d = np.ones(3)
print(unos1d)
print(unos1d.shape)

zeros2d = np.zeros((2, 3))
print(zeros2d)
print(zeros2d.shape)

[1. 1. 1.]
(3,)
[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [7]:
#Atención: No es lo mismo un array de una dimensión que una matriz de una fila

In [8]:
unos2d = np.ones((1,3))
print(unos2d)
print(unos2d.shape)

[[1. 1. 1.]]
(1, 3)


Para crear valores en espaciados dentro de un rango

In [9]:
rango = np.arange(2, 20, 3)
print(rango)
espaciados = np.linspace(2.0, 3.0, num=5)
print(espaciados)

[ 2  5  8 11 14 17]
[2.   2.25 2.5  2.75 3.  ]


# Operaciones básicas

Las operaciones con arrays son elemento a elemento

In [10]:
m1 = np.array([[1, 2, 3],
             [4, 5, 6 ]])
m2 = np.array([[1, 2, 3],
             [4, 5, 3],])

In [11]:
m1 + m2

array([[ 2,  4,  6],
       [ 8, 10,  9]])

In [12]:
m1 + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [13]:
m1 * m2

array([[ 1,  4,  9],
       [16, 25, 18]])

El producto entre matrices es con @ o dot()

In [14]:
m3 = m2.T
m3

array([[1, 4],
       [2, 5],
       [3, 3]])

In [47]:
m1 @ m3

array([[14, 23],
       [32, 59]])

In [16]:
m1.dot(m3)

array([[14, 23],
       [32, 59]])

De la misma manera, las condiciones se aplican a cada elemento del array. Se devuelve una array de boolean:

In [17]:
m1 > 3

array([[False, False, False],
       [ True,  True,  True]])

Hay operadores lógicos elemento a elemento


In [18]:
(m1 > 3) & (m1 < 6)

array([[False, False, False],
       [ True,  True, False]])

In [19]:
(m1 > 3) | (m1 < 6)

array([[ True,  True,  True],
       [ True,  True,  True]])

# Funciones universales

https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs

NumPy tiene una serie de funciones habituales predefinas que operan sobre cada elemento de un array

In [20]:
np.sqrt(m1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

#Métodos de ndarray

La clase ndarray tiene métodos para realizar operaciones sobre arrays.
Por ejemplo, sum(), max() y min() calculan la suma, el máximo y el mínimo de los elementos del array.
Los tres tienen un atributo axis, para especificar que el cálculo se haga a lo largo de un eje (filas, columnas).

In [21]:
m1.max()

np.int64(6)

In [22]:
m1.max(axis=0)

array([4, 5, 6])

In [23]:
m1.max(axis=1)

array([3, 6])

Se puede cambiar la forma de un array con la resize() y reshape()


In [59]:
m4 = np.arange(16)
m4[1]=10
print(m4)
m4.resize(4,5)
print(m4)



[ 0 10  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0 10  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15  0  0  0  0]]


In [60]:
m4 = np.arange(16)
m4[1]=10
m6 = m4.reshape(4,4) # no modifica la variable y los tamaños tienen que cuadrar
print(m4)
print(m6)
m7 = m4.reshape(2,-1)
print(m7)

[ 0 10  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0 10  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0 10  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, invert, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where

In [68]:
np.argmax(m7, axis = 1)

array([1, 7])

#Selección de intervalos

En los arrays 1D se siguen las mismas normas que en las listas de Python

In [27]:
vector1 = np.arange(1, 20, 2)
print(vector1)
print(vector1[3:7])
print(vector1[3:7:2])
print(vector1[::-1])
vector1[1:3] = 100
print(vector1)

for num in vector1:
  print(num, end = '_')

[ 1  3  5  7  9 11 13 15 17 19]
[ 7  9 11 13]
[ 7 11]
[19 17 15 13 11  9  7  5  3  1]
[  1 100 100   7   9  11  13  15  17  19]
1_100_100_7_9_11_13_15_17_19_

Para arrays multidimensionales se utiliza un índice para cada eje

In [28]:
grande = np.arange(30).reshape((5,6))
grande

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [29]:
# posición 1,4
grande[1, 4]

np.int64(10)

In [30]:
# todas las filas, columnas 2, 3 y 4
grande[:,2:5]

array([[ 2,  3,  4],
       [ 8,  9, 10],
       [14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [31]:
# toda la fila 1
grande[1,:]

array([ 6,  7,  8,  9, 10, 11])

In [32]:
# filas 1, 2 y 3
# columnas 2, 3 y 4
grande[1:4,2:5]

array([[ 8,  9, 10],
       [14, 15, 16],
       [20, 21, 22]])

In [33]:
# filas y columnas pares
grande[0:5:2, 0:6:2]

array([[ 0,  2,  4],
       [12, 14, 16],
       [24, 26, 28]])

Si el inicio o el fin del intervalo son la primera o última posición del array, no hace falta indicarlo

In [34]:
grande[::2, ::2]

array([[ 0,  2,  4],
       [12, 14, 16],
       [24, 26, 28]])

In [35]:
# filas pares, columnas 2, 3 y 4
grande[::2,2:5]

array([[ 2,  3,  4],
       [14, 15, 16],
       [26, 27, 28]])

La iteración se hace respecto al primer eje. Se puede usar el atributo flat para recorrer los elementos uno a uno

In [36]:
for fila in grande:
  print(fila)

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]


In [37]:
for num in grande.flat:
  print(num, end=' ')


0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 

También se puede indexar con un array de boolean

In [69]:
grande > 5

array([[False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [38]:
grande[grande > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29])

In [39]:
grande > 5

array([[False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

#Unión (stacking) de array

Es posible unir varios arrays vertical u horizontalmente si las dimensiones son correctas

In [40]:
np.hstack([m1, m2])


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 3]])

In [41]:
np.vstack((m1, m2))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 3]])

Con **column_stack()**  y **row_stack()** se puede crear una array 2D a partir de arrays 1D que se usan como columnas/filas

In [42]:
v1 = [4, 5, 6]
v2 = [7, 8, 9]
np.column_stack((v1, v2))

array([[4, 7],
       [5, 8],
       [6, 9]])

In [43]:
np.row_stack((v1, v2))

C:\Users\xabi\AppData\Local\Temp\ipykernel_10676\1919814030.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((v1, v2))


array([[4, 5, 6],
       [7, 8, 9]])

**concatenate()** permite especificar el eje a lo largo del cual se van a unir los arrays

In [44]:
np.concatenate((m1, m2), axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 3]])

In [45]:
np.concatenate((m1, m2), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 3]])